services:
  # приложение
  apartmentrentals:
    build: ./ApartmentRentals
    container_name: ApartmentRentals
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017/ApartmentRentals
    networks:
      - monitoring-network
    labels:
      - "app.name=ApartmentRentals"
    depends_on:
      - mongodb
      - redis 

#Db
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db        
    networks:
      - monitoring-network          
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring-network
    depends_on:
      - apartmentrentals

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-network
    depends_on:
      - prometheus

#Cache
  redis:
    image: redis:latest
    container_name: redis_container
    # environment:
    #   - REDIS_PASSWORD=${REDIS_PASSWORD}
    #   - REDIS_USER=${REDIS_USER}
    #   - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    networks:
      - monitoring-network  
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    # command: >
    #   sh -c '
    #     mkdir -p /usr/local/etc/redis &&
    #     echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
    #     echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
    #     echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
    #     echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
    #     echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
    #     echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
    #     redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
    #   '
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  monitoring-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  mongo_data: