global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Первое приложение
  - job_name: 'service1'
    static_configs:
      - targets: ['service1:8080']  # Имя контейнера + внутренний порт
    metrics_path: '/metrics'

  # Второе приложение
  - job_name: 'service2'
    static_configs:
      - targets: ['service2:8080']  # Имя контейнера + внутренний порт
    metrics_path: '/metrics'