global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Первое приложение
  - job_name: 'apartmentrentals'
    static_configs:
      - targets: ['apartmentrentals:8080']  # Имя контейнера + внутренний порт
    metrics_path: '/metrics'